#!/usr/bin/env bash
#displays To infinity and beyond indefinitely
#With a sleep 2 in between each iteration
#I am invincible!!! when receiving a SIGTERM signal
count=0
while [ $count -ge 0 ];
do
echo "To infiinity and beyond"
sleep 2
trap 'echo "I am invincible!!!"' SIGTERM
done
