#!/usr/bin/env bash
#diplays number 1 to 100
#diplays Fizzbuzz if number is a multiple of 3 and 5
#diplays Fizz if number is a multiple of 3
#diplays buzz if number is a multiple of 5
#else display the number in a list format
number=1
while [ $number -lt 101 ];
do
if [ $((number % 15)) -eq 0 ]
then
echo "FizzBuzz"

elif [ $((number % 3)) -eq 0 ]
then
echo "Fizz"
elif [ $((number % 5)) -eq 0 ]
then
echo "Buzz"
else
echo $number
fi
((number = number + 1))
done
