#!/usr/bin/env bash
#Displays 4 and then bad luck from china for 4th loop iteration, display 9 and then bad luck from japan for 9th loop iteratin
#Display 17 and then bad luck from italy for 17th iteration.
x=1;
while [ $x -le 20 ];
do
echo "$x";
case $x in 
4) echo "bad luck from China";;
9) echo "bad luck from Japan";;
17) echo "bad luck from Italy";
esac;
x=$((x + 1));
done
