#!/usr.bin/env bash
#configured contaiinerr to run Ndnix as user nginx
chown ngix:nginx /etc/ngnix/ngnix.conf
chown ngnix:ngnix /etc/ngnix/sites-available/default
chmod u+rwx /etc/nginx/nginx.conf
chmod u+rwx /etc/ngnix/sites-available/default
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
pkill apache2
su nginx service nginx restart
